relationship:
  - name: apmServiceCallsInfraElastiCacheRedisCluster
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "^Datastore/instance/Redis/[^/]*\\.cache.amazonaws\\.com/[0-9]+"
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSELASTICACHEREDISCLUSTER
          fields:
            - field: endpoint
              capture:
                attribute: metricName__4
            - field: port
              capture:
                attribute: metricName__5